#!/usr/bin/env js
var Assert = function () {
  "use strict";

  var AssertionError = function (msg) {
    var final = "Assertion failed: " + msg;
    console.error(final);
  };

  var args = arguments;
  var res  = true;

  for(var i = 0; i < args.length; i++) {
    var d   = ((i - 1) < 0) ? 0 : i - 1;
    res     = (args[i] === args[d]);
    if(!res || typeof res === "undefined" || res === null || res !== res) {
      throw new AssertionError(args[i] + " != " + args[d]);
    }
  }

  var atn = "not_undefined";

  try {
    atn = assert(res);
  } catch (e) {
    if(e instanceof ReferenceError) {
      return true;
    }
  }

  if(typeof atn === "undefined") {
    return true;
  }
};
// Generated by LispyScript v1.0.0
(require("http")).createServer(function(request,response) {
    response.writeHead(200,{'Content-Type': 'text/plain'});
    response.end((((request.socket.remoteAddress()).split(".")).map(parseFloat)).reduce(function(x,y) {
        return (x + y);
    }));
    return ((process.argv[2] || 1337)).listen;
});
