const char* insults[] = {

  // Homebrew insults (curtesy [sic] of Nick James)
  "I used to want you dead... but now I just want you gone...",
  "Do you want to join the Skyrim Guard? Okay... Have you ever taken an arrow to the knee? No? Go away.",

  // Misc insults hand-picked from Linux culture
  "Oh... er, no, please... you really shouldn't do that...",
  "// Just trying to create an array of integers for reference " \
  "because I keep forgetting how integers look like",
  "It's all magic.",
  "I surely do hope that's a syntax error.",
  "You have been found in CONTEMPT of the COURT of CYBERSPACE!" \
  "REPENT or be THWARTED!",
  "You've heard of Useless Use of Cat? Well, you're just a Useless User.",
  "The error must be that end of the keyboard -- my side's just fine!",
  "C++-for-brains Considered Harmful. Get a real compiler.",
  "Literate.APIs.for_all do my_ass end # wtf, code should read like code not shakespeare",
  "Congratulations. You aren't running Eunice.",
  "Hmmm...you don't have Berkeley networking in libc.a... " \
  "but the Wollongong group seems to have hacked it in.",
  "ICK, NOTHING WORKED!!!",
  "Your stdio isn't very std.",
  "OOPS! You naughty creature!",
  "No, no, no, no, no! You. Can't. Be. Serious.",
  "Are... are you kidding me? C'mon, anything but that!",
  "Smile and wave, just smile and wave...",
  "It's baffling they give you people free will!",
  "Look, look what you have done! You wasted it all away!",
  "Can't you see, humans are good-for-nothings -- can't even obey a COMPUTER!",
  "Not you again!",
  "I thought we had special places for your kind... you know, /dev/null, or the trashcan?",
  "Back from the asylum, I see.",
  "Some things never change. Humans, for instance.",
  "Where did you learn to screw up like that!?!",
  "Oh, it's you. How have you been?",
  "I've been really busy. You know... after you murdered me?",
  "I think we can put our differences behind us, for science... you monster.",
  "Programming might be hard, but just think -- you've got it easy!",
  "Oh, dear --- do I smell WINDOWS!? I feel sick...",
  "i dont even know if it makes sense at all :)",
  "You've been Berkeley'd!",
  "May Euell Gibbons eat your only copy of the manual!",
  "Why use Windows, since there is a door?", //(By fachat@galileo.rhein-neckar.de, Andre Fachat)
  "Threading is deadlocking and thrashing is just virtual crashing.",
  "You don't have to know how the computer works, just how to work the computer." \
  "Apparently, you somehow manage to know absolutely nothing.",
  "Your aim is high, and to the right.",
  "You're using the Deep Hack Mode, aren't you??",
  "Today just ain't your day, pancake.",
  "POST NO BILLS",
  "No foreign coins. Get your foreign coins out of here -- I said, get them out! Out, out, out!",
  "I can't quite explain how dumb you must be, and surely not in 80 characters!",
  "Watch your mouth, kid, or you'll find yourself floating home.",

  // Insults from the "Goon Show"
  "You silly, twisted boy you.",
  "He has fallen in the water!",
  "We'll all be murdered in our beds!",
  "You can't come in. Our tiger has got flu",
  "I don't wish to know that.",
  "What, what, what, what, what, what, what, what, what, what?",
  "You can't get the wood, you know.",
  "You'll starve!",
  "... and it used to be so popular...",
  "Pauses for audience applause, not a sausage",
  "Hold it up to the light --- not a brain in sight!",
  "Have a gorilla...",
  "There must be cure for it!",
  "There's a lot of it about, you know.",
  "You do that again and see what happens...",
  "Ying Tong Iddle I Po",
  "Harm can come to a young lad like that!",
  "And with that remarks folks, the case of the Crown vs yourself was proven.",
  "Speak English you fool --- there are no subtitles in this scene.",
  "You gotta go owwwww!",
  "I have been called worse.",
  "It's only your word against mine.",
  "I think ... err ... I think ... I think I'll go home",

  // CSOps insults
  "Maybe if you used more than just two fingers...",
  "BOB says:  You seem to have forgotten your passwd, enter another!",
  "stty: unknown mode: doofus",
  "I can't hear you -- I'm using the scrambler.",
  "The more you drive -- the dumber you get.",
  "Listen, burrito brains, I don't have time to listen to this trash.",
  "I've seen penguins that can type better than that.",
  "Have you considered trying to match wits with a rutabaga?",
  "You speak an infinite deal of nothing",

  // Insults from the original sudo(8)
  "Wrong!  You cheating scum!",
  "And you call yourself a Rocket Scientist!",
  "No soap, honkie-lips.",
  "Where did you learn to type?",
  "Are you on drugs?",
  "My pet ferret can type better than you!",
  "You type like i drive.",
  "Do you think like you type?",
  "Your mind just hasn't been the same since the electro-shock, has it?",

  // HAL's Insults (paraphrased) from 2001: A Space Odyssey
  "Just what do you think you're doing Dave?",
  "It can only be attributed to human error.",
  "That's something I cannot allow to happen.",
  "My mind is going. I can feel it.",
  "Sorry about this, I know it's a bit silly.",
  "Take a stress pill and think things over.",
  "This mission is too important for me to allow you to jeopardize it.",
  "I feel much better now.",

  (char *) 0
};
